version: "3.7"

services:
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    volumes:
      - /var/tachidesk:/home/suwayomi/.local/share/Tachidesk
    networks:
      - caddy
    ports:
      - 4567:4567
    restart: unless-stopped